### ISSUE TITLE
Laddar bara när man tar upp inställningar

### ISSUE THREAD

**Issue by vattlescout** [kmjonsson/google-docs-scoutnet-addon#1]
Går inte att komma åt inställningarna efter att man har skapat ett nytt projekt. Är det någon del av koden som saknas eller något bibliotek som ska kopplas?

**Comment by kmjonsson** [comment]
Det fungerar för mig (klassiskt citat).

Jag provade skapa ett helt nytt dokument, stoppa in koden från github, stänga ner dokumentet och starta upp det igen. Via scoutnet-menyn gå till inställningar, svara på behörighetsfrågan, och sedan köra det igen. Fungerade att ta upp dialogen med inställningar, ändra något stänga ner den, stänga dokumentet, öppna det igen och starta inställningsdialogen med de sparade inställningarna.

**Comment by vattlescout** [comment]
Visade sig vara min webbläsare som hade något fult trix för sig. :-(

**Comment by vattlescout** [comment]
Det verkar inte fungera i Google Chrome 👎

**Comment by kmjonsson** [comment]
Vad är det som inte fungerar i Chrome? testkörde precis och det fungerade utan problem.
